# Generated by Django 3.0.3 on 2022-02-15 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=50, verbose_name='姓名')),
                ('email', models.CharField(help_text='邮箱', max_length=50, verbose_name='邮箱')),
                ('subject', models.CharField(help_text='主题', max_length=50, verbose_name='主题')),
                ('message', models.TextField(default='', help_text='内容', verbose_name='内容')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, help_text='提交时间', verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '联系我的信息',
                'verbose_name_plural': '联系我的信息',
            },
        ),
        migrations.CreateModel(
            name='EducationExperienceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_experience_type', models.CharField(choices=[('0', '教育信息'), ('1', '职业履历')], help_text='数据类别选择', max_length=1, verbose_name='类别选择')),
                ('name', models.CharField(help_text='学校或者企业名称', max_length=30, verbose_name='学校或者企业名称')),
                ('duration_time', models.CharField(default='yyyy - yyyy', help_text='时间信息', max_length=13, verbose_name='时间信息')),
                ('info', models.CharField(help_text='学校或者企业介绍', max_length=50, verbose_name='学校或者企业介绍')),
            ],
            options={
                'verbose_name': '我的教育&职业履历列表',
                'verbose_name_plural': '我的教育&职业履历列表',
            },
        ),
        migrations.CreateModel(
            name='MyBlogList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='自媒体站点名称', max_length=30, verbose_name='自媒体站点名称')),
                ('info', models.CharField(help_text='自媒体简介', max_length=50, verbose_name='自媒体简介')),
                ('img', models.ImageField(blank=True, default='MyBlog/default.png', help_text='若没有选择封面，则使用默认封面', null=True, upload_to='MyBlog/', verbose_name='自媒体封面')),
                ('url', models.URLField(help_text='服务外链', max_length=500, verbose_name='服务外链')),
            ],
            options={
                'verbose_name': '自媒体列表',
                'verbose_name_plural': '自媒体列表',
            },
        ),
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_info', models.CharField(help_text='我的基本信息', max_length=255, verbose_name='我的基本信息')),
                ('full_name', models.CharField(help_text='我的姓名', max_length=10, verbose_name='我的姓名')),
                ('age', models.CharField(help_text='我的年龄', max_length=2, verbose_name='我的年龄')),
                ('address', models.CharField(help_text='我的地址', max_length=20, verbose_name='我的地址')),
                ('email', models.EmailField(help_text='我的邮箱', max_length=30, verbose_name='我的邮箱')),
                ('phone', models.CharField(help_text='联系电话', max_length=15, verbose_name='联系电话')),
                ('wechart', models.CharField(help_text='我的微信', max_length=20, verbose_name='我的微信')),
                ('job', models.CharField(help_text='我的职业', max_length=20, verbose_name='我的职业')),
                ('qq', models.CharField(help_text='我的QQ', max_length=20, verbose_name='我的QQ')),
                ('skill_info', models.CharField(help_text='技能基本信息', max_length=255, verbose_name='技能基本信息')),
                ('education_experience_info', models.CharField(help_text='教育&职业履历', max_length=255, verbose_name='教育&职业履历')),
                ('service_info', models.CharField(help_text='收费服务介绍', max_length=255, verbose_name='收费服务介绍')),
                ('site_info', models.CharField(help_text='自媒体介绍', max_length=255, verbose_name='自媒体介绍')),
            ],
            options={
                'verbose_name': '我的基本信息',
                'verbose_name_plural': '我的基本信息',
            },
        ),
        migrations.CreateModel(
            name='MyServiceProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_en', models.CharField(default='', help_text='英文类别名称', max_length=20, verbose_name='英文类别名称')),
                ('type_cn', models.CharField(help_text='中文类别名称', max_length=20, verbose_name='中文类别名称')),
            ],
            options={
                'verbose_name': '服务类别信息',
                'verbose_name_plural': '服务类别信息',
            },
        ),
        migrations.CreateModel(
            name='MyServiceProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='服务名称', max_length=30, verbose_name='服务名称')),
                ('info', models.CharField(help_text='服务简介', max_length=50, verbose_name='服务简介')),
                ('img', models.ImageField(blank=True, default='MyService/default.png', help_text='若没有选择封面，则使用默认封面', null=True, upload_to='MyService/', verbose_name='服务封面')),
                ('url', models.URLField(help_text='服务外链', max_length=500, verbose_name='服务外链')),
                ('type_name', models.ForeignKey(help_text='服务项目类别', on_delete=django.db.models.deletion.CASCADE, to='MyHomePage.MyServiceProjectType', verbose_name='服务项目类别')),
            ],
            options={
                'verbose_name': '我的服务明细',
                'verbose_name_plural': '我的服务明细',
            },
        ),
    ]
