# Generated by Django 3.0.3 on 2022-11-15 11:26

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('actual_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='用户姓名')),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户昵称')),
                ('gender', models.CharField(choices=[('Male', '男'), ('Female', '女'), ('Undefined', '未定义')], default='未定义', max_length=9, verbose_name='用户性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='用户生日')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='联系地址')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('user_image', models.ImageField(blank=True, default='UserImage/default.png', null=True, upload_to='UserImage', verbose_name='用户头像')),
                ('integral', models.IntegerField(default=0, help_text='积分', verbose_name='用户积分')),
                ('vip_level', models.IntegerField(default=0, help_text='等级', verbose_name='用户等级')),
                ('vip_exp', models.IntegerField(default=0, help_text='经验值', verbose_name='用户经验')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息列表',
                'verbose_name_plural': '用户信息列表',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
