# Generated by Django 3.0.3 on 2022-11-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信openid'),
        ),
    ]
